# Generated by Django 4.2.3 on 2025-08-02 17:54

import Ecommerce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0003_seller_sign_up_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=100, unique=True)),
                ('Product_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='product_details',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product_details',
            name='image',
            field=models.FileField(default=None, max_length=250, null=True, upload_to=Ecommerce.models.Products),
        ),
    ]
