# Generated by Django 4.2.3 on 2025-08-02 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0004_user_card_alter_product_details_desc_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_card',
            new_name='User_cart',
        ),
    ]
