# Generated by Django 4.2.3 on 2025-08-02 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0005_rename_user_card_user_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_cart',
            name='Product_id',
            field=models.CharField(max_length=100),
        ),
    ]
