# Generated by Django 4.2.3 on 2025-08-02 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0006_alter_user_cart_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_cart',
            name='user_email',
            field=models.EmailField(max_length=100),
        ),
    ]
