# Generated by Django 4.2.3 on 2025-10-04 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0007_alter_user_cart_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_details',
            name='available_quantity',
            field=models.IntegerField(default=1),
        ),
    ]
