# Generated by Django 4.2.3 on 2025-11-01 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0010_user_address_name_user_address_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_signup_details',
            name='Gender',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user_signup_details',
            name='phone_number',
            field=models.CharField(blank=True, default=None, max_length=15, null=True),
        ),
    ]
