# Generated by Django 4.2.3 on 2025-11-06 16:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0011_user_signup_details_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_ids', models.JSONField(default=list)),
                ('user_email', models.EmailField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('total_price', models.FloatField()),
                ('transaction_id', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('address', models.TextField()),
                ('order_status', models.CharField(default='Pending', max_length=50)),
                ('payment_status', models.CharField(default='Pending', max_length=50)),
                ('payment_method', models.CharField(default='COD', max_length=50)),
                ('order_date', models.DateTimeField(default=datetime.datetime(2025, 11, 6, 22, 10, 23, 204523))),
            ],
        ),
    ]
